{
 "title": "Lidarr",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(lidarr_system_status, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lidarr_system_status{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "artists",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lidarr_artists_total{job=\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "lidarr_artists_monitored_total{job=\"$instance\"}",
     "legendFormat": "monitored"
    }
   ]
  },
  {
   "title": "in queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lidarr_queue_total{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "health issues",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lidarr_system_health_issues{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lidarr_artists_filesize_bytes{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "albums",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lidarr_albums_total{job=\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "lidarr_albums_monitored_total{job=\"$instance\"}",
     "legendFormat": "monitored"
    }
   ]
  },
  {
   "title": "d/l past month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(lidarr_songs_downloaded_total{job=\"$instance\"}[30d]))"
    }
   ]
  },
  {
   "title": "songs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lidarr_songs_total{job=\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "lidarr_songs_missing_total{job=\"$instance\"}",
     "legendFormat": "missing"
    }
   ]
  },
  {
   "title": "d/ past week",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(lidarr_songs_downloaded_total{job=\"$instance\"}[7d]))"
    }
   ]
  },
  {
   "title": "qualities",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(lidarr_songs_quality_total{job=\"$instance\"}) by (quality))",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "qualities",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(lidarr_artists_genres_total{job=\"$instance\"} > 10) by (genre))",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "log",
   "type": "logs",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_name=\"lidarr\"} !~ \"Sending HTTP request to http://localhost:8686\""
    }
   ]
  }
 ]
}